config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :links, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

  resources :comments

  root 'links#index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path do %>
      <div class="navbar-brand"><%= image_tag "brand", width:"25", height:"25" %></div>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Submit link', new_link_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Settings', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li>
          <%= link_to "Connect with Facebook", user_omniauth_authorize_path(:facebook) %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>