config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :links, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

  resources :comments

  root 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
  validates :url, :format => URI::regexp(%w(http https))
  validates :title, presence: true
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :set_link, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :set_user, only: [:create, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @links = Link.all
  end

  def show
  end

  def new
    @link = Link.new
  end

  # save return either true or false; Create will return the model regardless
  # of whether the object was saved or not.
  # If you use create with branching logic you are at risk of silent failures
  # which is not the case if you use new + save.
  # create! doesn't suffer from the same issue as it raises and exception if
  # the record is invalid.
  # (.save! throws an error if saving fails)

  # same with .build; we still need to use .save
  # otherwise .create can be used w/out .save
  # .create! does the same as .create but raises ActiveRecord::RecordInvalid
  # if the record is invalid.
  def create
    @link = @user.links.build(link_params)
      if @link.save
        flash[:notice] = "Link was successfully created."
        redirect_to root_path
      else
        flash[:alert] = "Link must have a title and an URL. The URL must start with http://"
        redirect_to new_link_path
      end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      flash[:notice] = "Link was successfully updated."
      redirect_to link_path
    else
      flash[:alert] = "Link must have a title and an URL. The URL must start with http://"
      redirect_to edit_link_path
    end
  end

  def destroy
    @link.destroy
    flash[:notice] = "Link was successfully deleted."
    redirect_to root_path
  end

  def upvote
    @link.liked_by @user
    redirect_to_back_or_default
  end

  def downvote
    @link.downvote_from @user
    redirect_to_back_or_default
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # if your user user cannot access a resource in the application because :back
    # depends on the request header variable HTTP_REFERER, this might be
    # the case if the user is for example trying to access the resource with
    # a direct link (e.g. a bookmark or a link from an email). Then use this
    def redirect_to_back_or_default(default = root_url)
      if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        redirect_to :back
      else
        redirect_to default
      end
    end

end

app/helpers/links_helper.rb
require 'embedly'
require 'json'

module LinksHelper

  def display(url)
    embedly_api = Embedly::API.new(key: ENV['EB_KEY'])

    obj = embedly_api.oembed :url => url
    if obj.first.type == "video"
      raise (obj.first.html).html_safe
    elsif obj.first.type == "photo"
      clean_url = obj.first.url.sub(/([?]fb)+$/, '')
      raise %Q{ <p><img src="#{clean_url}" alt="#{obj.first.title}"style="width:100%"></p> }.html_safe
    else
      %Q{ <p><img src="http://i.imgur.com/B7jmNAw.png" alt="not found" style="width:100%"></p> }.html_safe
    end

    # obj = embedly_api.oembed :url => url
    # puts obj[0].marshal_dump
    # json_obj = JSON.pretty_generate(obj[0].marshal_dump)
    # puts json_obj
  end

  def title(url)
    embedly_api = Embedly::API.new(key: ENV['EB_KEY'])

    obj = embedly_api.oembed :url => url
    (obj.first.title).html_safe
  end

  def thumbnail(url)
    # should be more efficient to store the thumbnail 65x65 instead of retrieving the whole file
    embedly_api = Embedly::API.new(key: ENV['EB_KEY'])

    obj = embedly_api.oembed :url => url
    if obj.first.type != "error"
      %Q{ <img class="media-object" src="#{obj.first.thumbnail_url+"?meow"}" alt="#{obj.first.title}" style="width:64px;height:64px;"> }.html_safe
    else
      %Q{ <img class="media-object" src="http://i.imgur.com/B7jmNAw.png" alt="not found" style="width:64px;height:64px;"> }.html_safe
    end

  end
end

app/views/links/edit.html.erb
<div class="container">

  <h2 class="text-center">Edit link</h2>
  <%= form_for(@link, :html => {:class => "form-horizontal"}) do |f| %>

    <div class="form-group">
      <%= f.label :title, class: "col-sm-4 control-label"  %>
      <div class="col-sm-4">
      <%= f.text_field :title, class: "form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :url, class: "col-sm-4 control-label"  %>
      <div class="col-sm-4">
      <%= f.text_field :url, class: "form-control"  %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-4">
      <%= f.submit "Update", class: "btn btn-default" %>
      </div>
      (<%= link_to('back home', root_path)%>)
    </div>

  <% end %>

</div>

app/views/links/index.html.erb
<div class="container">

  <h1>Purr... here the latest cute furry animals</h1>

  <hr>

  <% @links.each do |link| %>
    <div class="media">
      <div class="media-left">
        <a href="<%= link_path(link) %>">
          <%= thumbnail(link.url) %>
        </a>
      </div>
      <div class="media-body">
        <h2 class="media-heading">
        <%= link_to link.title, link %><br>
        <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></small>
        </h2>
      </div>
    </div>

    <div class="btn-group">
      <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
      <%= link_to link_path(link), class: "btn btn-default btn-sm" do %>
        <%= pluralize_comment(link.comments.count, "comment") %>
      <% end %>
      <% if current_user == link.user %>
        <%= link_to('Delete', link_path(link), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm") %>
        <%= link_to('edit', edit_link_path(link), class: "btn btn-default btn-sm") %>
      <% end %>
      <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span> Upvote <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down"> Downvote <%= link.get_downvotes.size %>
      <% end %>
    </div>

  <% end %>

</div>

app/views/links/new.html.erb
<div class="container">

  <h2 class="text-center">Create new link</h2>

    <%= form_for(@link, :html => {:class => "form-horizontal"}) do |f| %>

      <div class="form-group">
        <%= f.label :title, class: "col-sm-4 control-label"  %>
        <div class="col-sm-4">
        <%= f.text_field :title, class: "form-control"  %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :url, class: "col-sm-4 control-label"  %>
        <div class="col-sm-4">
        <%= f.text_field :url, class: "form-control"  %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-4">
        <%= f.submit "Create", class: "btn btn-default" %>
        </div>
        (<%= link_to('back home', root_path)%>)
      </div>

    <% end %>

</div>

app/views/links/show.html.erb
<div class="container">
(<%= link_to('back home', root_path)%>)

  <div class="row">
    <div class="col-md-8">

      <h2><%= @link.title %></h2>
      <h3><%= title(@link.url) %><br />
        <small class="author">Submitted about <%= time_ago_in_words(@link.created_at) %> by <%= @link.user.email %></small>
      </h3>

      <%= display(@link.url) %>


      <div class="btn-group">
        <a class="btn btn-default btn-sm" href="<%= @link.url %>">Visit Link</a>
        <% if current_user == @link.user %>
          <%= link_to('Delete', link_path(@link), method: :delete, class: "btn btn-default btn-sm") %>
          <%= link_to('edit', edit_link_path(@link), class: "btn btn-default btn-sm") %>
        <% end %>
        <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= @link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down">
          Downvote
          <%= @link.get_downvotes.size %>
        <% end %>
      </div>

      <hr>

      <h4>Add a comment</h4>
      <%= simple_form_for [@link, Comment.new]  do |f| %>
        <div class="field">
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <br>
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      <% end %>

      <hr>

      <% @link.comments.each do |comment| %>
        <p><%= comment.body %> -- <small class="author">Submitted about <%= time_ago_in_words(comment.created_at) %> by <%= comment.user.email %>
        <% if comment.user == current_user || comment.link.user == current_user %>
          ( <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %> )
          <% end %></small>
        <% end %>
      </p><br />

    </div>
    <div class="col-md-4">
      <p>ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads ads </p>
    </div>

  </div>

</div>


<% content_for :widthurl do %>
  <script type="text/javascript">
    $("iframe").each(
        function(index, elem) {
            elem.setAttribute("width","100%");
        }
    );
  </script>
<% end %>